@port=3000
@jwt={{login.response.body.data.token}}

###
GET http://localhost:{{port}}/api/v1/workouts?page=2&pageSize=30
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ2Yzc5MDc3ZjczY2VhNWU0ODE4NmQiLCJuYW1lIjoiSm9obiBEb2UiLCJlbWFpbCI6ImpvaG5AZG9lLmNvbSIsInBob3RvIjoiaHR0cHM6Ly9yb2JvaGFzaC5vcmcvaGljdmVsZGljdGEucG5nP3NpemU9NTB4NTAmc2V0PXNldDEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE2ODIzNjM2MjcsImV4cCI6MTY4MjQ1MDAyN30.ybb286CRlkT8sbL9Nii7FIgbbzhy3QatKlVXVUMwei8

###
GET http://localhost:{{port}}/api/v1/workouts/getWorkoutsTest

###
GET http://localhost:{{port}}/

###
GET http://localhost:{{port}}/api/v1/workouts/Humza Shah

###
GET http://localhost:{{port}}/api/v1/workouts/1

###
POST http://localhost:{{port}}/api/v1/workouts/deleteWorkout
Content-Type: application/json
some-other-header: with my very personal information

{
    "duration": 25,
    "name": "Benching",
    "username": "Humza Shah"

}


###
POST http://localhost:{{port}}/api/v1/workouts
Content-Type: application/json
some-other-header: with my very personal information

{
    "date": "2023-03-19",
    "duration": 25,
    "name": "Random1",
    "username": "Humza Shah"

}

###
DELETE http://localhost:{{port}}/api/v1/workouts/1

###
GET http://localhost:{{port}}/api/v1/products/search/bridge



###
# @name login
POST http://localhost:{{port}}/api/v1/users/login
Content-Type: application/json

{
    "email": "H@101",
    "password": "123456"
}

###
GET http://localhost:3000/api/v1/users/

###
GET http://localhost:3000/api/v1/users/Humza Shah

###
POST http://localhost:3000/api/v1/workouts/seed

###
POST http://localhost:3000/api/v1/users/seed

###
GET http://localhost:3000/api/v1/users/getWorkouts/H@101

###
POST http://localhost:3000/api/v1/users/addWorkout/H@101
Content-Type: application/json

{
    "date": "2021-01-01",
    "duration": "10",
    "name": "benching"
}