###
GET http://localhost:3000/

###
GET http://localhost:3000/api/v1/workouts

###
GET http://localhost:3000/api/v1/products/1

###
POST http://localhost:3000/api/v1/workouts
Content-Type: application/json
some-other-header: with my very personal information

{
    "date": "2023-03-19",
    "duration": 10,
    "name": "Cowddwwddwdw"

}

###
DELETE http://localhost:3000/api/v1/products/1

###
GET http://localhost:3000/api/v1/products/search/bridge